In [2]:
import numpy as np
from pandas import DataFrame, read_csv
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

dataset = pd.read_feather('complete.feather')
dataset.drop(['special','ID','name','full_name','club','club_logo','league','birth_date','real_face', 'flag','nationality','photo','eur_value','eur_wage','eur_release_clause','overall','potential','pac','sho','pas','dri','def','phy'], axis=1,inplace=True)
dataset.drop(dataset.columns[[x for x in range (135,162)]], axis=1,inplace=True) #71 for just excluding traits fields.

display(dataset.head())


age  height_cm  weight_kg   body_type  international_reputation  \
0   32      185.0       80.0  C. Ronaldo                         5   
1   30      170.0       72.0       Messi                         5   
2   25      175.0       68.0      Neymar                         5   
3   30      182.0       86.0      Normal                         5   
4   31      193.0       92.0      Normal                         5   

   skill_moves  weak_foot work_rate_att work_rate_def preferred_foot  \
0            5          4          High           Low          Right   
1            4          4        Medium        Medium           Left   
2            5          5          High        Medium          Right   
3            4          4          High        Medium          Right   
4            1          4        Medium        Medium          Right   

               ...               playmaker_speciality  engine_speciality  \
0              ...                              False              False   
1              ...                              False              False   
2              ...                              False              False   
3              ...                              False              False   
4              ...                              False              False   

   distance_shooter_speciality  crosser_speciality  \
0                         True               False   
1                        False               False   
2                        False               False   
3                        False               False   
4                        False               False   

   free_kick_specialist_speciality  tackling_speciality  tactician_speciality  \
0                            False                False                 False   
1                             True                False                 False   
2                            False                False                 False   
3                            False                False                 False   
4                            False                False                 False   

   acrobat_speciality  strength_speciality  clinical_finisher_speciality  
0                True                False                          True  
1                True                False                          True  
2                True                False                         False  
3                True                False                          True  
4               False                False                         False  

[5 rows x 135 columns]

In [22]:
y = pd.DataFrame(dataset[dataset.columns[44:71]])
X = pd.DataFrame(dataset[dataset.columns[:44]])
y.drop(['rs','ls','lf','rf','rcm','lcm','ram','lam','ldm','rdm','rcb','lcb'],axis=1,inplace=True)
display(y.head())
display(X.head())
i=0
for name in X.columns:
    print(str(i) + ': '+ name)
    i+=1
#display(X.columns)

rw    rm    rb   rwb    st    lw    cf   cam    cm    lm   cdm    cb  \
0  91.0  89.0  61.0  66.0  92.0  91.0  91.0  89.0  82.0  89.0  62.0  53.0   
1  91.0  90.0  57.0  62.0  88.0  91.0  92.0  92.0  84.0  90.0  59.0  45.0   
2  89.0  87.0  59.0  64.0  84.0  89.0  88.0  88.0  79.0  87.0  59.0  46.0   
3  87.0  85.0  64.0  68.0  88.0  87.0  88.0  87.0  80.0  85.0  65.0  58.0   
4   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

     lb   lwb    gk  
0  61.0  66.0   NaN  
1  57.0  62.0   NaN  
2  59.0  64.0   NaN  
3  64.0  68.0   NaN  
4   NaN   NaN  92.0

age  height_cm  weight_kg   body_type  international_reputation  \
0   32      185.0       80.0  C. Ronaldo                         5   
1   30      170.0       72.0       Messi                         5   
2   25      175.0       68.0      Neymar                         5   
3   30      182.0       86.0      Normal                         5   
4   31      193.0       92.0      Normal                         5   

   skill_moves  weak_foot work_rate_att work_rate_def preferred_foot  \
0            5          4          High           Low          Right   
1            4          4        Medium        Medium           Left   
2            5          5          High        Medium          Right   
3            4          4          High        Medium          Right   
4            1          4        Medium        Medium          Right   

      ...       penalties  composure  marking  standing_tackle  \
0     ...              85         95       22               31   
1     ...              78         96       13               28   
2     ...              81         92       21               24   
3     ...              85         83       30               45   
4     ...              47         70       10               10   

   sliding_tackle  gk_diving  gk_handling  gk_kicking  gk_positioning  \
0              23          7           11          15              14   
1              26          6           11          15              14   
2              33          9            9          15              15   
3              38         27           25          31              33   
4              11         91           90          95              91   

   gk_reflexes  
0           11  
1            8  
2           11  
3           37  
4           89  

[5 rows x 44 columns]

0: age
1: height_cm
2: weight_kg
3: body_type
4: international_reputation
5: skill_moves
6: weak_foot
7: work_rate_att
8: work_rate_def
9: preferred_foot
10: crossing
11: finishing
12: heading_accuracy
13: short_passing
14: volleys
15: dribbling
16: curve
17: free_kick_accuracy
18: long_passing
19: ball_control
20: acceleration
21: sprint_speed
22: agility
23: reactions
24: balance
25: shot_power
26: jumping
27: stamina
28: strength
29: long_shots
30: aggression
31: interceptions
32: positioning
33: vision
34: penalties
35: composure
36: marking
37: standing_tackle
38: sliding_tackle
39: gk_diving
40: gk_handling
41: gk_kicking
42: gk_positioning
43: gk_reflexes


In [23]:
X['body_type'] = np.where(X.body_type.isin(['Stocky','Lean','Normal']),X.body_type,'Unique')

X_dummy = pd.get_dummies(X['body_type'],prefix='body_type')
X_dummy = X_dummy.join(pd.get_dummies(X['work_rate_att'],prefix='work_rate_att'))
X_dummy = X_dummy.join(pd.get_dummies(X['work_rate_def'],prefix='work_rate_def'))
X_dummy = X_dummy.join(pd.get_dummies(X['preferred_foot'],prefix='preferred_foot'))
for i in range(44,len(X.columns)):
    X_dummy = X_dummy.join(pd.get_dummies(X[X.columns[i]],prefix=X.columns[i]))
for i in range(44,len(X.columns)):
    X.drop(X.columns[44],axis=1,inplace=True)
X_dummy.drop('preferred_foot_Left',axis=1,inplace=True)
X.drop('body_type',axis=1,inplace=True)
X.drop('work_rate_att',axis=1,inplace=True)
X.drop('work_rate_def',axis=1,inplace=True)
X.drop('preferred_foot',axis=1,inplace=True)
X = X.join(X_dummy)

X = X.as_matrix()
y = y.as_matrix()
#display(X_dummy.head())

In [24]:
from pylab import rcParams
rcParams['figure.figsize'] = 15, 15

#ax = sns.heatmap(X.corr())
#plt.show()

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
np.nan_to_num(y_train,copy=False)
np.nan_to_num(y_test,copy=False)

array([[49., 53., 66., ..., 66., 64.,  0.],
       [87., 85., 58., ..., 58., 63.,  0.],
       [50., 51., 49., ..., 49., 49.,  0.],
       ...,
       [62., 64., 63., ..., 63., 64.,  0.],
       [60., 62., 54., ..., 54., 56.,  0.],
       [68., 68., 47., ..., 47., 51.,  0.]])

In [ ]:
from sklearn.neural_network import MLPRegressor

model = MLPRegressor(hidden_layer_sizes=(300,200), activation='relu', solver='adam', alpha=0.0000, learning_rate='adaptive', 
                     learning_rate_init=0.0001, power_t=0.5, max_iter=200, tol=0.0001, verbose=True, early_stopping=False)

ann = model.fit(X_train, y_train)

In [27]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
linReg = model.fit(X_train, y_train)

In [34]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor(max_depth=20,min_samples_split=15, min_samples_leaf=6)
tree = model.fit(X_train, y_train)

In [35]:
def evaluate(model, X, y):
    predictions = model.predict(X)
    
    y_test_ranks = np.argmax(y, axis=1)
    predictions_ranks = np.argmax(predictions, axis=1)
    index=0
    misses=0
    for x in predictions_ranks:
        if(max(y[index]) != y[index][predictions_ranks[index]]):
            misses+=1
#            print(str(y_labels[index]) + '\tvs\t' + str(predictions.astype(int)[index]))
        index+=1

    print('Accuracy = ' + str(1 - misses/len(y_test_ranks)))

print("ANN Test Data Accuracy")
#evaluate(ann, X_test, y_test)
print("ANN Train Data Accuracy")
#evaluate(ann, X_train, y_train)
print("Linear Regression Test Data Accuracy")
evaluate(linReg, X_test, y_test)
print("Linear Regression Train Data Accuracy")
evaluate(linReg, X_train, y_train)
print("Decision Tree Test Data Accuracy")
evaluate(tree, X_test, y_test)
print("Decision Tree Train Data Accuracy")
evaluate(tree, X_train, y_train)


ANN Test Data Accuracy
ANN Train Data Accuracy
Linear Regression Test Data Accuracy
Accuracy = 0.9975921466938322
Linear Regression Train Data Accuracy
Accuracy = 0.9975387058356491
Decision Tree Test Data Accuracy
Accuracy = 0.7521763289498056
Decision Tree Train Data Accuracy
Accuracy = 0.8145295752282652


In [ ]:
# Ignore code onwards from here !!!!!!!!

In [107]:
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

class ANN:
    def __init__(self):
        self.layers=5 #including input and output
        self.units = [51,80,50,40,1]#27]
        
        # seed random numbers to make calculation
        # deterministic (just a good practice)
        np.random.seed(1)
        self.alpha = 0.00001
        
        # initialize weights randomly with mean 0
        self.syn0 = 2*np.random.random((self.units[0]+1,self.units[1])) - 1
        self.syn1 = 2*np.random.random((self.units[1]+1,self.units[2])) - 1
        self.syn2 = 2*np.random.random((self.units[2]+1,self.units[3])) - 1
        self.syn3 = 2*np.random.random((self.units[3]+1,self.units[4])) - 1

    
    def forward(self, X):
        m = len(X)
        self.l0 = np.ones((m,len(self.syn0)))         # Add bias column
        self.l0[:,1:] = X

        self.l1 = np.ones((m,len(self.syn1)))         # Add bias column
        self.l1[:,1:] = nonlin(np.dot(self.l0,self.syn0))

        self.l2 = np.ones((m,len(self.syn2)))         # Add bias column
        self.l2[:,1:] = nonlin(np.dot(self.l1,self.syn1))

        self.l3 = np.ones((m,len(self.syn3)))         # Add bias column
        self.l3[:,1:] = nonlin(np.dot(self.l2,self.syn2))

        self.l4 = np.dot(self.l3,self.syn3)
        return self.l4
    
    def backward(self, y):
        # how much did we miss?
        self.l4_error = (y - self.l4)
        np.nan_to_num(self.l4_error,copy=False)

        # in what direction is the target value?
        # were we really sure? if so, don't change too much.
        self.l4_delta = self.l4_error
        # how much did each l2 value contribute to the l2 error (according to the weights)?
        self.l3_error = self.l4_delta.dot(self.syn3.T)
        self.l3_delta = self.l3_error* nonlin(self.l3,deriv=True)
        self.l2_error = self.l3_delta[:,1:].dot(self.syn2.T)
        self.l2_delta = self.l2_error* nonlin(self.l2,deriv=True)
        self.l1_error = self.l2_delta[:,1:].dot(self.syn1.T)
        self.l1_delta = self.l1_error* nonlin(self.l1,deriv=True)
        
        self.syn3 += self.l3.T.dot(self.l4_delta) * self.alpha
        self.syn2 += self.l2.T.dot(self.l3_delta[:,1:]) * self.alpha
        self.syn1 += self.l1.T.dot(self.l2_delta[:,1:]) * self.alpha
        self.syn0 += self.l0.T.dot(self.l1_delta[:,1:]) * self.alpha
    
ann = ANN()
for iter in range(50000):
    ann.forward(X_train)
    ann.backward(y_train)
    
    if (iter% 100) == 0:
        print("Error:" + str(np.mean(np.abs(ann.l4_error))))
        print(ann.l4.shape)

ValueError: could not broadcast input array from shape (12595,165) into shape (12595,51)

In [75]:
ann.forward(X_test)

predictions = np.nan_to_num(ann.l4)
y_test2 = np.nan_to_num(y_test)

y_test_ranks = np.argmax(y_test2, axis=1)
predictions_ranks = np.argmax(predictions, axis=1)
misses = np.count_nonzero(y_test_ranks != predictions_ranks)

print(misses)
print(len(y_test_ranks))

print('Accuracy = ' + str(1 - misses/len(y_test_ranks)))

print(y_test_ranks)
print(predictions_ranks)

4777
5399
Accuracy = 0.11520651972587514
[ 1  6  7 ...  7  0 26]
[26 26 26 ... 26 26 26]


In [119]:
ann.forward(X_train)

predictions = np.nan_to_num(ann.l4)
y_train2 = np.nan_to_num(y_train)

y_ranks = np.argmax(y_train2, axis=1)
predictions_ranks = np.argmax(predictions, axis=1)
misses = np.count_nonzero(y_ranks != predictions_ranks)

print(misses)
print(len(y_ranks))

print('Accuracy = ' + str(1 - misses/len(y_ranks)))


print(y_ranks)
print(predictions_ranks)


0
12595
Accuracy = 1.0
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


c:\users\sohaib zahid\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: overflow encountered in exp
  after removing the cwd from sys.path.


In [120]:
print(ann.l4[5:20,:])
print(y_train[5:20,:])

[[58.21089842]
 [58.21089842]
 [58.21089842]
 [58.21089842]
 [58.21089842]
 [58.21089842]
 [58.21089842]
 [58.21089842]
 [58.21089842]
 [58.21089842]
 [58.21112726]
 [58.21097368]
 [58.21071825]
 [58.21089842]
 [58.21089842]]
[[61.]
 [49.]
 [47.]
 [41.]
 [65.]
 [45.]
 [71.]
 [59.]
 [70.]
 [50.]
 [nan]
 [nan]
 [nan]
 [58.]
 [60.]]
